// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pustalorc.GlobalBan.Database;

namespace Pustalorc.GlobalBan.Migrations
{
    [DbContext(typeof(GlobalBanDbContext))]
    [Migration("20210305170753_FixCast")]
    partial class FixCast
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Pustalorc.GlobalBan.API.Classes.PlayerBan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<string>("Hwid")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasMaxLength(64);

                    b.Property<long>("Ip")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsUnbanned")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("varchar(512)")
                        .HasMaxLength(512);

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeOfBan")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Pustalorc_GlobalBan_PlayerBans");
                });
#pragma warning restore 612, 618
        }
    }
}
